[build]
  command = "npm run build"   # Ensures Vite build command runs
  publish = "dist"            # Specifies where the output files are located

[build.environment]
  NODE_VERSION = "20"         # Matches Netlify's Node.js version
  PYTHON_VERSION = "3.10"     # Matches Python version explicitly
